# Generated by Django 4.0.3 on 2022-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('locador', 'Locador'), ('propietario', 'Propietário')], default='locador', max_length=12),
        ),
    ]
