# Generated by Django 4.0.3 on 2022-04-16 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=250)),
                ('recuperado', models.CharField(default='nao', max_length=3)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 23, 41, 6, 781805, tzinfo=utc))),
            ],
        ),
    ]
