# Generated by Django 4.0.3 on 2022-04-22 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='validade',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 16, 32, 28, 157987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('locador', 'Locador'), ('proprietario', 'Proprietário')], default='locador', max_length=12),
        ),
    ]
