# Generated by Django 4.0.3 on 2022-04-05 22:58

from django.db import migrations, models
import django.db.models.deletion
import imoveis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65, verbose_name='Título')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=65, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=65, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=65, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=65, verbose_name='Estado')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do aluguel')),
                ('paga_deposito', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Paga depósito?')),
                ('valor_deposito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor do depósito')),
                ('paga_iptu', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Paga IPTU?')),
                ('valor_iptu', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor do IPTU')),
                ('paga_incendio', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Paga taxa de icêndio?')),
                ('valor_incendio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor da taxa de incêndio')),
                ('paga_luz', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Paga luz?')),
                ('paga_agua', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Paga água?')),
                ('qtd_quarto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Qtd. Quartos')),
                ('qtd_banheiro', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Qtd. Banheiros')),
                ('qtd_vaga', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Qtd. Vagas')),
                ('idependente', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Casa idependente?')),
                ('aceita_pet', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Aceita Pet?')),
                ('aceita_crianca', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Aceita criança?')),
                ('comunidade', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='É comunidade?')),
                ('comunidade_nome', models.CharField(blank=True, default='', max_length=65, verbose_name='Nome da comunidade')),
                ('tipo_teto', models.CharField(choices=[('laje', 'Laje'), ('telhado', 'Telhado'), ('ambos', 'Ambos')], default='laje', max_length=8, verbose_name='Tipo do teto')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição do imóvel')),
                ('disponivel', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Disponível para locação?')),
                ('data_anuncio', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Imoveis',
            },
        ),
        migrations.CreateModel(
            name='ImovelFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=imoveis.models.content_file_name)),
                ('imovel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
