# Generated by Django 4.0.3 on 2022-04-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovelfoto',
            options={'default_related_name': 'imoveisfotos'},
        ),
    ]
