# Generated by Django 4.0.3 on 2022-04-06 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovelfoto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovelfoto',
            options={},
        ),
        migrations.AlterField(
            model_name='imovelfoto',
            name='imovel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imoveisfoto', to='imoveis.imovel'),
        ),
    ]
