# Generated by Django 4.0.3 on 2022-04-12 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Vamos fechar negócio?', max_length=65)),
                ('propietario', models.IntegerField(default=0)),
                ('imovel_id', models.IntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locador', models.IntegerField(default=0)),
                ('propietario', models.IntegerField(default=0)),
                ('mensagem', models.TextField(default='')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lida', models.CharField(default='nao', max_length=3)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensagem.chat')),
            ],
        ),
    ]
