# Generated by Django 4.0.3 on 2022-04-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagens',
            options={'default_related_name': 'chatmensagens'},
        ),
    ]
