# Generated by Django 4.0.3 on 2022-04-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_alter_mensagens_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagens',
            old_name='locador',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='mensagens',
            old_name='propietario',
            new_name='destinatario',
        ),
    ]
