# Generated by Django 4.0.3 on 2022-04-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_rename_locador_mensagens_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
