# Generated by Django 4.0.3 on 2022-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0004_alter_mensagens_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
